version: '2'
services:
  db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    ipam:
     config:
       - subnet: 192.168.100.0/24
         gateway: 192.168.100.1